# Generated by Django 4.2 on 2024-03-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "mail",
                    models.EmailField(max_length=254, verbose_name="email"),
                ),
            ],
        ),
    ]
