# Generated by Django 4.2 on 2024-03-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="mail",
            field=models.EmailField(max_length=100, verbose_name="email"),
        ),
    ]
