# Generated by Django 4.2 on 2024-02-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbstractCatalog",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("Название", models.CharField(max_length=150)),
                ("Опубликовано", models.BooleanField(default=True)),
            ],
        ),
    ]
