stages:
  - linting
  - black
  - adrestest

before_script:
  - pip3 install -r requirements/dev.txt
  - pip3 install -r requirements/test.txt

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --import-order-style=google --inline-quotes=double .

black:
  stage: black
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

adrestest:
  stage: adrestest
  script:
    - cd lyceum
    - python manage.py test
