stages:
  - linting
  - black

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .
black:
  stage: black
  image: python:3.10
  script:
    - pip install black
    - black --check .
