stages:
  - linting
  - black
  - deploy

before_script:
  - pip install -r requirements/dev.txt

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .
    - pip install pep8-naming
    - pip install import-order
    - pip install flake8-quotes
    - flake8 --inline-quotes=double
    
black:
  stage: black
  image: python:3.12
  script:
    - black --check .
deploy:
  stage: deploy
  image: python:3.12
  script:
    - pip install -r requirements/prod.txt
