stages:
  - linting
  - black
  - deploy

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .
    - flake8 --inline-quotes=double
    
black:
  stage: black
  image: python:3.10
  script:
    - pip install black
    - black --check .
deploy:
  stage: deploy
  image: python:3.10
  script:
    - pip install -r requirements/prod.txt
    - pip install -r requirements/dev.txt
