stages:
  - linting
  - black
  - adrestest

before_script:
  - pip install -r requirements/dev.txt
  - pip install -r requirements/test.txt

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --inline-quotes=double --import-order-style=google .

black:
  stage: black
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

adrestest:
  stage: adrestest
  image: python:3.10
  script:
    - cd lyceum
    - python manage.py test

Badge:
  stage: build
  image: python:3.6
  before_script:
    - echo "Python other dependencies installation"
    - pip install anybadge
  script:
    - anybadge -l "Last Commit" -v "$(date '+%d.%m.%Y %H:%M')" -f last-commit.svg -c green
  artifacts:
    paths:
      - last-commit.svg
    when: always
    expire_in: 4 weeks
