stages:
  - linting
  - black
  - adrestest

before_script:
  - pip install -r requirements/dev.txt

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/test.txt
    - flake8 --inline-quotes=double

black:
  stage: black
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

adrestest:
  stage: adrestest
  script:
    - pythom manage.py test
