[tool.black]
line-length = 79
target-version = ['py310', 'py311', 'py312']
exclude = '''
/(
  | migrations
  | \.venv         # exclude a few common directories in the
  | \.git          # root of the project
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.eggs
  | _build
  | buck-out
  | build
  | dist
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)/
'''