# Generated by Django 4.2 on 2024-02-29 19:35

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите навзание', max_length=150, unique=True, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, help_text='выберите будет ли опубликовано', verbose_name='опубликовано')),
                ('slug', models.SlugField(help_text='Напишите слаг(Eng)', max_length=200, unique=True, verbose_name='слаг')),
                ('weight', models.IntegerField(default=100, help_text='Введите вес', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32767)], verbose_name='вес')),
                ('normalization_data', models.CharField(editable=False, max_length=150, unique=True, verbose_name='правильные данные')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='картинки')),
            ],
            options={
                'verbose_name': 'Картинки',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='главное изображение')),
            ],
            options={
                'verbose_name': 'Главное изображение',
                'verbose_name_plural': 'Главное изображение',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите навзание', max_length=150, unique=True, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, help_text='выберите будет ли опубликовано', verbose_name='опубликовано')),
                ('slug', models.SlugField(help_text='Напишите слаг(Eng)', max_length=200, unique=True, verbose_name='слаг')),
                ('normalization_data', models.CharField(editable=False, max_length=150, unique=True, verbose_name='правильные данные')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите навзание', max_length=150, unique=True, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, help_text='выберите будет ли опубликовано', verbose_name='опубликовано')),
                ('text', models.TextField(help_text='Описание товара', validators=[catalog.validators.ValidatorArg('превосходно', 'роскошно')], verbose_name='текст')),
                ('category', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категории')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.images', verbose_name='Изображения')),
                ('main_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.mainimage', verbose_name='Главное изображение')),
                ('tags', models.ManyToManyField(related_name='item', to='catalog.tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
