# Generated by Django 4.2 on 2024-02-19 21:24

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogCategory",
            fields=[
                (
                    "abstractcatalog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractcatalog",
                    ),
                ),
                (
                    "Слаг",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                "invalid",
                            )
                        ],
                    ),
                ),
                (
                    "Вес",
                    models.IntegerField(
                        default=100,
                        validators=[
                            catalog.models.minvaluevalidator,
                            catalog.models.maxvaluevalidator,
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
            },
            bases=("core.abstractcatalog",),
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "abstractcatalog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractcatalog",
                    ),
                ),
                (
                    "Текст",
                    models.TextField(
                        validators=[catalog.models.words_in_text]
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        default="овощи",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.catalogcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товар",
            },
            bases=("core.abstractcatalog",),
        ),
        migrations.CreateModel(
            name="CatalogTag",
            fields=[
                (
                    "abstractcatalog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractcatalog",
                    ),
                ),
                (
                    "Слаг",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                "invalid",
                            )
                        ],
                    ),
                ),
                ("item", models.ManyToManyField(to="catalog.catalogitem")),
            ],
            options={
                "verbose_name": "тег",
            },
            bases=("core.abstractcatalog",),
        ),
    ]
