# Generated by Django 4.2 on 2024-03-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.images', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.mainimage', verbose_name='Главное изображение'),
        ),
    ]
