# Generated by Django 4.2 on 2024-02-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CatalogCategory",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="CatalogItem",
            new_name="Item",
        ),
        migrations.RenameModel(
            old_name="CatalogTag",
            new_name="Tag",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "товар", "verbose_name_plural": "товары"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "тег", "verbose_name_plural": "теги"},
        ),
    ]
