# Generated by Django 4.2 on 2024-02-21 10:55

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_catalogcategory_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="выберите будет ли опубликовано",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите навзание",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(
                help_text="Напишите слаг(Eng)",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.IntegerField(
                default=100,
                help_text="Введите вес",
                validators=[
                    catalog.models.minvaluevalidator,
                    catalog.models.maxvaluevalidator,
                ],
                verbose_name="Вес",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.category",
                verbose_name="категории",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="выберите будет ли опубликовано",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                help_text="Введите навзание",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="выберите будет ли опубликовано",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Введите навзание",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(
                help_text="Напишите слаг(Eng)",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="слаг",
            ),
        ),
    ]
