# Generated by Django 4.2 on 2024-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="normalization_data",
            field=models.CharField(
                default=0,
                editable=False,
                max_length=150,
                unique=True,
                verbose_name="Правильные данные",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="normalization_data",
            field=models.CharField(
                default=0,
                editable=False,
                max_length=150,
                unique=True,
                verbose_name="Правильные данные",
            ),
            preserve_default=False,
        ),
    ]
