# Generated by Django 4.2 on 2024-02-22 18:03

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_item_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Описание товара",
                validators=[catalog.models.validator_take_arg],
                verbose_name="Текст",
            ),
        ),
    ]
