# Generated by Django 4.2 on 2024-02-26 15:14

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_category_normalization_data_tag_normalization_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/")),
            ],
        ),
        migrations.CreateModel(
            name="MainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/")),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="normalization_data",
            field=models.CharField(
                editable=False,
                max_length=150,
                unique=True,
                verbose_name="правильные данные",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Напишите слаг(Eng)",
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Описание товара",
                validators=[
                    catalog.validators.ValidatorArg("превосходно", "роскошно")
                ],
                verbose_name="текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalization_data",
            field=models.CharField(
                editable=False,
                max_length=150,
                unique=True,
                verbose_name="правильные данные",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="images",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.images",
                verbose_name="Картинки товара",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.mainimage",
                verbose_name="Главная картинка товара",
            ),
        ),
    ]
