# Generated by Django 4.2 on 2024-02-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0004_images_mainimage_alter_category_normalization_data_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={
                "verbose_name": "Картинки",
                "verbose_name_plural": "Картинки",
            },
        ),
        migrations.AlterModelOptions(
            name="mainimage",
            options={
                "verbose_name": "Главное изображение",
                "verbose_name_plural": "Главное изображение",
            },
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="картинки"),
        ),
        migrations.AlterField(
            model_name="item",
            name="images",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.images",
                verbose_name="Изображения",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.mainimage",
                verbose_name="Главное изображение",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(
                upload_to="", verbose_name="главное изображение"
            ),
        ),
    ]
