# Generated by Django 4.2 on 2024-03-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_category_normalization_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(upload_to="catalog/images/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(upload_to="catalog/mainimage/%Y/%m/%d"),
        ),
    ]
