# Generated by Django 4.2 on 2024-05-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профиль",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.DateField(null=True),
        ),
    ]
