# Generated by Django 4.2 on 2024-03-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(upload_to="mainimage/"),
        ),
    ]
