# Generated by Django 4.2 on 2024-03-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_images_image_alter_mainimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(upload_to="catalog/images/"),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(upload_to="catalog/mainimage/"),
        ),
    ]
