# Generated by Django 4.2 on 2024-03-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_item_options_alter_images_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalization_data",
            field=models.CharField(
                editable=False,
                max_length=150,
                verbose_name="правильные данные",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalization_data",
            field=models.CharField(
                editable=False,
                max_length=150,
                verbose_name="правильные данные",
            ),
        ),
    ]
