# Generated by Django 4.2 on 2024-05-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_basket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basket",
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзина",
            },
        ),
    ]
