# Generated by Django 4.2 on 2024-05-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_basket_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Описание товара", verbose_name="текст"
            ),
        ),
    ]
