# Generated by Django 4.2 on 2024-05-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_rename_item_basket_item_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basket",
            old_name="item_id",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="basket",
            old_name="user_id",
            new_name="user",
        ),
    ]
